<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLMutations\CreateCoupon;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLMutations\DeleteCoupon;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLMutations\UpdateCoupon;
use GraphQL\Type\Definition\ObjectType;

class RootMutationType {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if (self::$instance === null) {
			self::$instance = new ObjectType([
				'name' => 'Mutation',
				'fields' => fn() => [
					'CreateCoupon' => CreateCoupon::getFieldDefinition(),
					'DeleteCoupon' => DeleteCoupon::getFieldDefinition(),
					'UpdateCoupon' => UpdateCoupon::getFieldDefinition(),
				],
			]);
		}
		return self::$instance;
	}
}
