<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries\GetCoupon;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries\ListCoupons;
use GraphQL\Type\Definition\ObjectType;

class RootQueryType {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if (self::$instance === null) {
			self::$instance = new ObjectType([
				'name' => 'Query',
				'fields' => fn() => [
					'Coupon' => GetCoupon::getFieldDefinition(),
					'Coupons' => ListCoupons::getFieldDefinition(),
				],
			]);
		}
		return self::$instance;
	}
}
