<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api\Scripts;

use Automattic\WooCommerce\Api\Attributes\ArrayOf;
use Automattic\WooCommerce\Api\Attributes\ConnectionOf;
use Automattic\WooCommerce\Api\Attributes\Deprecated;
use Automattic\WooCommerce\Api\Attributes\Description;
use Automattic\WooCommerce\Api\Attributes\Ignore;
use Automattic\WooCommerce\Api\Attributes\Name;
use Automattic\WooCommerce\Api\Attributes\Parameter;
use Automattic\WooCommerce\Api\Attributes\ParameterDescription;
use Automattic\WooCommerce\Api\Attributes\PublicAccess;
use Automattic\WooCommerce\Api\Attributes\RequiredCapability;
use Automattic\WooCommerce\Api\Attributes\ScalarType;
use Automattic\WooCommerce\Api\Attributes\Unroll;

class ApiBuilder {
	private const API_DIR = __DIR__ . '/../../../Api';
	private const AUTOGENERATED_DIR = __DIR__ . '/../Autogenerated';
	private const TEMPLATES_DIR = __DIR__ . '/../Templates';
	private const API_NAMESPACE = 'Automattic\\WooCommerce\\Api';
	private const AUTOGENERATED_NAMESPACE = 'Automattic\\WooCommerce\\Internal\\Api\\Autogenerated';

	/** @var array<string, array{class: \ReflectionClass|\ReflectionEnum, kind: string, ignored: bool}> */
	private array $classes = [];

	/** @var array<string, string> Map of PHP FQCN => GraphQL name */
	private array $graphql_names = [];

	/** @var string[] Errors collected during validation */
	private array $errors = [];

	/** @var string[] Warnings collected during build */
	private array $warnings = [];

	/** @var array Discovered connections: ['node_type' => FQCN, 'source' => string] */
	private array $connections = [];

	// Counters for summary.
	private int $query_count = 0;
	private int $mutation_count = 0;
	private int $type_count = 0;
	private int $input_type_count = 0;
	private int $enum_count = 0;
	private int $scalar_count = 0;

	public function build(): void {
		// PHP version check.
		if ( PHP_VERSION_ID < 80100 ) {
			fwrite( STDERR, sprintf(
				"Error: PHP 8.1 or later is required to run the API build script. Current version: %s.\n",
				PHP_VERSION
			) );
			exit( 2 );
		}

		echo "Scanning src/Api/ for code API classes...\n";

		$this->discover();
		$this->validate();

		if ( ! empty( $this->errors ) ) {
			fwrite( STDERR, "Build failed with errors:\n" );
			foreach ( $this->errors as $error ) {
				fwrite( STDERR, "  - {$error}\n" );
			}
			exit( 1 );
		}

		$this->wipeAutogenerated();
		$this->createDirectoryStructure();
		$this->generate();
		$this->writeTimestamp();

		// Regenerate autoloader.
		$wc_dir = realpath( __DIR__ . '/../../../..' );
		echo "Regenerating autoloader...\n";
		exec( "composer dump-autoload --working-dir=" . escapeshellarg( $wc_dir ) . " 2>&1", $output, $code );
		if ( $code !== 0 ) {
			echo "Warning: composer dump-autoload failed: " . implode( "\n", $output ) . "\n";
		}

		// Print summary.
		echo "\n=== Build Complete ===\n";
		echo "  Queries:     {$this->query_count}\n";
		echo "  Mutations:   {$this->mutation_count}\n";
		echo "  Types:       {$this->type_count}\n";
		echo "  Input Types: {$this->input_type_count}\n";
		echo "  Enums:       {$this->enum_count}\n";
		echo "  Scalars:     {$this->scalar_count}\n";
		echo "  Connections: " . count( $this->connections ) . "\n";

		if ( ! empty( $this->warnings ) ) {
			echo "\nWarnings:\n";
			foreach ( $this->warnings as $warning ) {
				echo "  - {$warning}\n";
			}
		}
	}

	// ========================================================================
	// Discovery
	// ========================================================================

	private function discover(): void {
		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( self::API_DIR, \FilesystemIterator::SKIP_DOTS )
		);

		foreach ( $iterator as $file ) {
			if ( $file->getExtension() !== 'php' ) {
				continue;
			}

			$fqcn = $this->fileToFqcn( $file->getPathname() );
			if ( $fqcn === null ) {
				continue;
			}

			$kind = $this->classifyByNamespace( $fqcn );
			if ( $kind === null || $kind === 'attribute' || $kind === 'exception' ) {
				continue;
			}

			try {
				if ( enum_exists( $fqcn ) ) {
					$ref = new \ReflectionEnum( $fqcn );
				} else {
					$ref = new \ReflectionClass( $fqcn );
				}
			} catch ( \ReflectionException $e ) {
				$this->warnings[] = "Could not reflect {$fqcn}: {$e->getMessage()}";
				continue;
			}

			$ignored = ! empty( $ref->getAttributes( Ignore::class ) );

			$this->classes[ $fqcn ] = [
				'class'   => $ref,
				'kind'    => $kind,
				'ignored' => $ignored,
			];

			// Compute GraphQL name.
			$name_attr = $ref->getAttributes( Name::class );
			$graphql_name = ! empty( $name_attr )
				? $name_attr[0]->newInstance()->name
				: $ref->getShortName();

			$this->graphql_names[ $fqcn ] = $graphql_name;
		}

		echo "  Found " . count( $this->classes ) . " classes.\n";
	}

	private function fileToFqcn( string $filepath ): ?string {
		$rel = str_replace( realpath( self::API_DIR ) . '/', '', realpath( $filepath ) );
		$rel = str_replace( '.php', '', $rel );
		$rel = str_replace( '/', '\\', $rel );
		return self::API_NAMESPACE . '\\' . $rel;
	}

	private function classifyByNamespace( string $fqcn ): ?string {
		$relative = substr( $fqcn, strlen( self::API_NAMESPACE ) + 1 );
		$parts    = explode( '\\', $relative );
		$top_dir  = $parts[0];

		return match ( $top_dir ) {
			'Queries'    => 'query',
			'Mutations'  => 'mutation',
			'Types'      => 'type',
			'InputTypes' => 'input_type',
			'Enums'      => 'enum',
			'Interfaces' => 'interface',
			'Scalars'    => 'scalar',
			'Pagination' => 'pagination',
			'Attributes' => 'attribute',
			default      => $fqcn === self::API_NAMESPACE . '\\ApiException' ? 'exception' : null,
		};
	}

	// ========================================================================
	// Validation
	// ========================================================================

	private function validate(): void {
		foreach ( $this->classes as $fqcn => $info ) {
			if ( $info['ignored'] ) {
				continue;
			}

			$ref  = $info['class'];
			$kind = $info['kind'];

			match ( $kind ) {
				'query', 'mutation' => $this->validateCommand( $fqcn, $ref ),
				'type'              => $this->validateOutputType( $fqcn, $ref ),
				'input_type'        => $this->validateInputType( $fqcn, $ref ),
				'enum'              => $this->validateEnum( $fqcn, $ref ),
				'scalar'            => $this->validateScalar( $fqcn, $ref ),
				default             => null,
			};
		}
	}

	private function validateCommand( string $fqcn, \ReflectionClass $ref ): void {
		// Must have execute method.
		if ( ! $ref->hasMethod( 'execute' ) ) {
			$this->errors[] = "Query/Mutation \"{$ref->getShortName()}\" must have an execute method.";
			return;
		}

		// Capability check.
		$caps = $this->resolveCapabilities( $ref );
		$has_public = ! empty( $ref->getAttributes( PublicAccess::class ) );

		if ( empty( $caps ) && ! $has_public ) {
			$this->errors[] = "Query/Mutation \"{$ref->getShortName()}\" has no RequiredCapability attribute (directly or inherited) and no PublicAccess attribute.";
		}

		if ( ! empty( $caps ) && $has_public ) {
			$this->errors[] = "Query/Mutation \"{$ref->getShortName()}\" cannot have both RequiredCapability and PublicAccess.";
		}
	}

	private function validateOutputType( string $fqcn, \ReflectionClass $ref ): void {
		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			if ( ! empty( $prop->getAttributes( Ignore::class ) ) ) {
				continue;
			}
			$this->validatePropertyType( $prop, 'output', $ref->getShortName() );
		}
	}

	private function validateInputType( string $fqcn, \ReflectionClass $ref ): void {
		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			if ( ! empty( $prop->getAttributes( Ignore::class ) ) ) {
				continue;
			}
			$this->validatePropertyType( $prop, 'input', $ref->getShortName() );
		}
	}

	private function validatePropertyType( \ReflectionProperty $prop, string $context, string $class_name ): void {
		$type = $prop->getType();
		if ( $type === null ) {
			$this->errors[] = "Property \"{$class_name}::\${$prop->getName()}\" must have a type declaration.";
			return;
		}

		if ( $type instanceof \ReflectionNamedType && $type->getName() === 'array' ) {
			if ( empty( $prop->getAttributes( ArrayOf::class ) ) && empty( $prop->getAttributes( ConnectionOf::class ) ) ) {
				$this->errors[] = "Property \"{$class_name}::\${$prop->getName()}\" is typed as array but has no #[ArrayOf] attribute.";
			}
		}
	}

	private function validateEnum( string $fqcn, \ReflectionEnum $ref ): void {
		if ( ! $ref->isBacked() ) {
			$this->errors[] = "Enum \"{$ref->getShortName()}\" must be a backed enum (string or int).";
		}
	}

	private function validateScalar( string $fqcn, \ReflectionClass $ref ): void {
		if ( ! $ref->hasMethod( 'serialize' ) || ! $ref->hasMethod( 'parse' ) ) {
			$this->errors[] = "Scalar \"{$ref->getShortName()}\" must have static serialize and parse methods.";
		}
	}

	private function resolveCapabilities( \ReflectionClass $ref ): array {
		$caps = [];

		// Direct attributes.
		foreach ( $ref->getAttributes( RequiredCapability::class ) as $attr ) {
			$caps[] = $attr->newInstance()->capability;
		}

		// Parent classes.
		$parent = $ref->getParentClass();
		if ( $parent ) {
			foreach ( $parent->getAttributes( RequiredCapability::class ) as $attr ) {
				$caps[] = $attr->newInstance()->capability;
			}
		}

		// Traits.
		foreach ( $ref->getTraits() as $trait ) {
			foreach ( $trait->getAttributes( RequiredCapability::class ) as $attr ) {
				$caps[] = $attr->newInstance()->capability;
			}
		}

		// Interfaces.
		foreach ( $ref->getInterfaces() as $iface ) {
			foreach ( $iface->getAttributes( RequiredCapability::class ) as $attr ) {
				$caps[] = $attr->newInstance()->capability;
			}
		}

		return array_unique( $caps );
	}

	// ========================================================================
	// Generation
	// ========================================================================

	private function wipeAutogenerated(): void {
		if ( is_dir( self::AUTOGENERATED_DIR ) ) {
			$this->rmdirRecursive( self::AUTOGENERATED_DIR );
		}
	}

	private function createDirectoryStructure(): void {
		$dirs = [
			self::AUTOGENERATED_DIR,
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Output',
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Input',
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Enums',
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Interfaces',
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Scalars',
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Pagination',
			self::AUTOGENERATED_DIR . '/GraphQLQueries',
			self::AUTOGENERATED_DIR . '/GraphQLMutations',
		];

		foreach ( $dirs as $dir ) {
			if ( ! is_dir( $dir ) ) {
				mkdir( $dir, 0755, true );
			}
		}
	}

	private function generate(): void {
		$queries   = [];
		$mutations = [];

		foreach ( $this->classes as $fqcn => $info ) {
			if ( $info['ignored'] || $info['kind'] === 'pagination' ) {
				continue;
			}

			$ref  = $info['class'];
			$kind = $info['kind'];

			match ( $kind ) {
				'enum'       => $this->generateEnum( $fqcn, $ref ),
				'scalar'     => $this->generateScalar( $fqcn, $ref ),
				'type'       => $this->generateOutputType( $fqcn, $ref ),
				'input_type' => $this->generateInputType( $fqcn, $ref ),
				'query'      => $queries[ $fqcn ] = $ref,
				'mutation'   => $mutations[ $fqcn ] = $ref,
				default      => null,
			};
		}

		// Pre-scan connections from queries/mutations (ConnectionOf on execute methods).
		$this->discoverConnections( $queries, $mutations );

		// Generate connections (PageInfo first since connections reference it).
		$this->generatePageInfo();
		foreach ( $this->connections as $conn ) {
			$this->generateConnection( $conn['node_type'] );
		}

		// Generate resolvers.
		foreach ( $queries as $fqcn => $ref ) {
			$this->generateResolver( $fqcn, $ref, 'query' );
		}
		foreach ( $mutations as $fqcn => $ref ) {
			$this->generateResolver( $fqcn, $ref, 'mutation' );
		}

		// Generate FieldArgumentExtractor.
		$this->generateFieldArgumentExtractor();

		// Generate root types.
		$this->generateRootQueryType( $queries );
		$this->generateRootMutationType( $mutations );
	}

	private function discoverConnections( array $queries, array $mutations ): void {
		foreach ( array_merge( $queries, $mutations ) as $fqcn => $ref ) {
			if ( ! $ref->hasMethod( 'execute' ) ) {
				continue;
			}
			$method    = $ref->getMethod( 'execute' );
			$conn_attr = $method->getAttributes( ConnectionOf::class );
			if ( ! empty( $conn_attr ) ) {
				$node_type = $conn_attr[0]->newInstance()->type;
				$this->connections[ $node_type ] = [
					'node_type' => $node_type,
					'source'    => $ref->getShortName() . '::execute()',
				];
			}
		}
	}

	// ------ Enum ------

	private function generateEnum( string $fqcn, \ReflectionEnum $ref ): void {
		$graphql_name = $this->graphql_names[ $fqcn ];
		$description  = $this->getDescription( $ref );
		$enum_alias   = $ref->getShortName() . 'Enum';

		$values = [];
		foreach ( $ref->getCases() as $case ) {
			$case_name_attr = $case->getAttributes( Name::class );
			$gql_case_name  = ! empty( $case_name_attr )
				? $case_name_attr[0]->newInstance()->name
				: $this->toScreamingSnakeCase( $case->getName() );

			$deprecation = $case->getAttributes( Deprecated::class );

			$values[] = [
				'graphql_name'       => $gql_case_name,
				'case_name'          => $case->getName(),
				'description'        => $this->getDescription( $case ),
				'deprecation_reason' => ! empty( $deprecation ) ? $deprecation[0]->newInstance()->reason : null,
			];
		}

		$code = $this->renderTemplate( 'EnumTypeTemplate.php', [
			'namespace'    => self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Enums',
			'class_name'   => $ref->getShortName(),
			'graphql_name' => $graphql_name,
			'description'  => $description,
			'enum_fqcn'    => $fqcn,
			'enum_alias'   => $enum_alias,
			'values'       => $values,
		] );

		$path = self::AUTOGENERATED_DIR . '/GraphQLTypes/Enums/' . $ref->getShortName() . '.php';
		file_put_contents( $path, $code );
		++$this->enum_count;
	}

	// ------ Scalar ------

	private function generateScalar( string $fqcn, \ReflectionClass $ref ): void {
		$graphql_name = $this->graphql_names[ $fqcn ];
		$description  = $this->getDescription( $ref );
		$scalar_alias = $ref->getShortName() . 'Scalar';

		$code = $this->renderTemplate( 'ScalarTypeTemplate.php', [
			'namespace'    => self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Scalars',
			'class_name'   => $ref->getShortName(),
			'graphql_name' => $graphql_name,
			'description'  => $description,
			'scalar_fqcn'  => $fqcn,
			'scalar_alias' => $scalar_alias,
		] );

		$path = self::AUTOGENERATED_DIR . '/GraphQLTypes/Scalars/' . $ref->getShortName() . '.php';
		file_put_contents( $path, $code );
		++$this->scalar_count;
	}

	// ------ Output Type ------

	private function generateOutputType( string $fqcn, \ReflectionClass $ref ): void {
		$graphql_name  = $this->graphql_names[ $fqcn ];
		$description   = $this->getDescription( $ref );
		$use_stmts     = [];
		$interfaces    = [];
		$fields        = [];

		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			if ( ! empty( $prop->getAttributes( Ignore::class ) ) ) {
				continue;
			}

			$field = $this->buildFieldDefinition( $prop, 'output', $use_stmts );
			if ( $field !== null ) {
				$fields[] = $field;
			}
		}

		$code = $this->renderTemplate( 'ObjectTypeTemplate.php', [
			'namespace'      => self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Output',
			'class_name'     => $ref->getShortName(),
			'graphql_name'   => $graphql_name,
			'description'    => $description,
			'use_statements' => array_unique( $use_stmts ),
			'interfaces'     => $interfaces,
			'fields'         => $fields,
		] );

		$path = self::AUTOGENERATED_DIR . '/GraphQLTypes/Output/' . $ref->getShortName() . '.php';
		file_put_contents( $path, $code );
		++$this->type_count;
	}

	// ------ Input Type ------

	private function generateInputType( string $fqcn, \ReflectionClass $ref ): void {
		$graphql_name = $this->graphql_names[ $fqcn ];

		// Strip "Input" suffix for generated class name, but keep it for GraphQL name.
		$gen_class_name = $ref->getShortName();
		if ( str_ends_with( $gen_class_name, 'Input' ) ) {
			$gen_class_name = substr( $gen_class_name, 0, -5 );
		}

		$description = $this->getDescription( $ref );
		$use_stmts   = [];
		$fields      = [];

		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			if ( ! empty( $prop->getAttributes( Ignore::class ) ) ) {
				continue;
			}

			$field = $this->buildFieldDefinition( $prop, 'input', $use_stmts );
			if ( $field !== null ) {
				$fields[] = $field;
			}
		}

		$code = $this->renderTemplate( 'InputObjectTypeTemplate.php', [
			'namespace'      => self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Input',
			'class_name'     => $gen_class_name,
			'graphql_name'   => $graphql_name,
			'description'    => $description,
			'use_statements' => array_unique( $use_stmts ),
			'fields'         => $fields,
		] );

		$path = self::AUTOGENERATED_DIR . '/GraphQLTypes/Input/' . $gen_class_name . '.php';
		file_put_contents( $path, $code );
		++$this->input_type_count;
	}

	// ------ Resolver ------

	private function generateResolver( string $fqcn, \ReflectionClass $ref, string $kind ): void {
		$graphql_name  = $this->graphql_names[ $fqcn ];
		$description   = $this->getDescription( $ref );
		$command_alias = $ref->getShortName() . 'Command';
		$use_stmts     = [];

		$execute_method = $ref->getMethod( 'execute' );
		$params         = $execute_method->getParameters();

		// Determine return type.
		$return_type      = $execute_method->getReturnType();
		$connection_of    = $execute_method->getAttributes( ConnectionOf::class );
		$has_connection_of = ! empty( $connection_of );

		$return_type_expr = $this->getReturnTypeExpr( $execute_method, $use_stmts );

		// Build args and execute params.
		$args           = [];
		$execute_params = [];
		$input_converters = [];

		foreach ( $params as $param ) {
			$param_name = $param->getName();

			// Infrastructure parameters.
			if ( $param_name === '_requested_fields' || $param_name === '_field_arguments' ) {
				$execute_params[] = [
					'name'              => $param_name,
					'conversion'        => null,
					'is_infrastructure' => true,
				];
				continue;
			}

			$param_type = $param->getType();
			$type_name  = $param_type instanceof \ReflectionNamedType ? $param_type->getName() : 'mixed';

			// Unroll: expand each property of the class into a separate GraphQL arg.
			if ( $this->shouldUnroll( $param, $type_name ) ) {
				$unroll = $this->buildUnrollInfo( $type_name, $use_stmts );
				foreach ( $unroll['args'] as $uarg ) {
					$args[] = $uarg;
				}
				$execute_params[] = [
					'name'              => $param_name,
					'conversion'        => null,
					'is_infrastructure' => false,
					'unroll'            => $unroll,
				];
				continue;
			}

			$arg_type_expr = $this->phpTypeToGraphQLExpr( $type_name, $param_type?->allowsNull() ?? false, $param, $use_stmts );

			$param_description = $this->getParamDescription( $param );

			$arg_entry = [
				'name'        => $param_name,
				'type_expr'   => $arg_type_expr,
				'description' => $param_description,
				'has_default' => $param->isDefaultValueAvailable(),
				'default'     => $param->isDefaultValueAvailable() ? $param->getDefaultValue() : null,
			];
			$args[] = $arg_entry;

			// Determine conversion for execute params.
			$conversion = null;
			$input_info = $this->getClassInfo( $type_name );

			if ( $input_info !== null && $input_info['kind'] === 'input_type' ) {
				// Input type: needs conversion.
				$converter_name = 'convert' . ( new \ReflectionClass( $type_name ) )->getShortName();
				$conversion     = "self::{$converter_name}(\$args['{$param_name}'])";

				// Build converter if not already done.
				if ( ! isset( $input_converters[ $type_name ] ) ) {
					$input_converters[ $type_name ] = $this->buildInputConverter( $type_name );
				}
			} elseif ( $input_info !== null && $input_info['kind'] === 'enum' ) {
				$from_expr  = "\\{$type_name}::from(\$args['{$param_name}'])";
				$conversion = ( $param_type?->allowsNull() )
					? "\$args['{$param_name}'] !== null ? {$from_expr} : null"
					: $from_expr;
			}

			$execute_params[] = [
				'name'              => $param_name,
				'conversion'        => $conversion,
				'is_infrastructure' => false,
			];
		}

		// Capabilities.
		$caps          = $this->resolveCapabilities( $ref );
		$public_access = ! empty( $ref->getAttributes( PublicAccess::class ) );

		$dir_name  = $kind === 'query' ? 'GraphQLQueries' : 'GraphQLMutations';
		$namespace = self::AUTOGENERATED_NAMESPACE . '\\' . $dir_name;

		$code = $this->renderTemplate( 'QueryResolverTemplate.php', [
			'namespace'            => $namespace,
			'class_name'           => $ref->getShortName(),
			'graphql_name'         => $graphql_name,
			'description'          => $description,
			'command_fqcn'         => $fqcn,
			'command_alias'        => $command_alias,
			'return_type_expr'     => $return_type_expr,
			'use_statements'       => array_unique( $use_stmts ),
			'args'                 => $args,
			'capabilities'         => $caps,
			'public_access'        => $public_access,
			'has_connection_of'    => $has_connection_of,
			'connection_type_alias' => '',
			'execute_params'       => $execute_params,
			'input_converters'     => array_values( $input_converters ),
		] );

		$path = self::AUTOGENERATED_DIR . "/{$dir_name}/" . $ref->getShortName() . '.php';
		file_put_contents( $path, $code );

		if ( $kind === 'query' ) {
			++$this->query_count;
		} else {
			++$this->mutation_count;
		}
	}

	/**
	 * Whether a parameter should be unrolled into flat GraphQL args.
	 */
	private function shouldUnroll( \ReflectionParameter $param, string $type_name ): bool {
		// Attribute on the parameter itself.
		if ( ! empty( $param->getAttributes( Unroll::class ) ) ) {
			return true;
		}

		// Attribute on the class.
		if ( class_exists( $type_name ) ) {
			$ref = new \ReflectionClass( $type_name );
			if ( ! empty( $ref->getAttributes( Unroll::class ) ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Build unroll metadata: the list of GraphQL args and constructor properties
	 * derived from the public properties of the given class.
	 */
	private function buildUnrollInfo( string $fqcn, array &$use_stmts ): array {
		$ref        = new \ReflectionClass( $fqcn );
		$args       = [];
		$properties = [];

		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			if ( ! empty( $prop->getAttributes( Ignore::class ) ) ) {
				continue;
			}

			$prop_name = $prop->getName();
			$type      = $prop->getType();
			$type_name = $type instanceof \ReflectionNamedType ? $type->getName() : 'mixed';
			$nullable  = $type?->allowsNull() ?? false;

			// Description from attribute.
			$desc_attrs   = $prop->getAttributes( Description::class );
			$description  = ! empty( $desc_attrs ) ? $desc_attrs[0]->newInstance()->description : '';

			// Default value.
			$has_default = $prop->hasDefaultValue();
			$default     = $has_default ? $prop->getDefaultValue() : null;

			// If promoted, the default may come from the constructor parameter.
			if ( ! $has_default && $prop->isPromoted() ) {
				$ctor = $ref->getConstructor();
				if ( $ctor !== null ) {
					foreach ( $ctor->getParameters() as $ctor_param ) {
						if ( $ctor_param->getName() === $prop_name && $ctor_param->isDefaultValueAvailable() ) {
							$has_default = true;
							$default     = $ctor_param->getDefaultValue();
							break;
						}
					}
				}
			}

			// GraphQL type expression.
			$type_expr = $this->phpTypeToGraphQLExpr( $type_name, $nullable, $prop, $use_stmts );

			$args[] = [
				'name'        => $prop_name,
				'type_expr'   => $type_expr,
				'description' => $description,
				'has_default' => $has_default,
				'default'     => $default,
			];

			// Value expression for the constructor call.
			$class_info = $this->getClassInfo( $type_name );
			if ( $class_info !== null && $class_info['kind'] === 'enum' ) {
				$from_expr  = "\\{$type_name}::from(\$args['{$prop_name}'])";
				$value_expr = $nullable
					? "\$args['{$prop_name}'] !== null ? {$from_expr} : null"
					: $from_expr;
			} else {
				$value_expr = "\$args['{$prop_name}']";
				if ( $has_default ) {
					$value_expr .= ' ?? ' . var_export( $default, true );
				}
			}

			$properties[] = [
				'name'       => $prop_name,
				'value_expr' => $value_expr,
			];
		}

		return [
			'fqcn'       => $fqcn,
			'args'       => $args,
			'properties' => $properties,
		];
	}

	private function buildInputConverter( string $input_fqcn ): array {
		$ref         = new \ReflectionClass( $input_fqcn );
		$method_name = 'convert' . $ref->getShortName();
		$properties  = [];

		foreach ( $ref->getProperties( \ReflectionProperty::IS_PUBLIC ) as $prop ) {
			$type      = $prop->getType();
			$type_name = $type instanceof \ReflectionNamedType ? $type->getName() : 'mixed';

			$conversion = null;
			$class_info = $this->getClassInfo( $type_name );

			if ( $class_info !== null && $class_info['kind'] === 'enum' ) {
				$from_expr  = "\\{$type_name}::from(\$data['{$prop->getName()}'])";
				$conversion = ( $type?->allowsNull() )
					? "\$data['{$prop->getName()}'] !== null ? {$from_expr} : null"
					: $from_expr;
			}
			// Nested input types could be handled recursively here.

			$properties[] = [
				'name'       => $prop->getName(),
				'conversion' => $conversion,
			];
		}

		return [
			'method_name' => $method_name,
			'input_fqcn'  => $input_fqcn,
			'input_class' => $ref->getShortName(),
			'properties'  => $properties,
		];
	}

	// ------ Connection ------

	private function generateConnection( string $node_type_fqcn ): void {
		$node_ref  = $this->classes[ $node_type_fqcn ]['class'] ?? new \ReflectionClass( $node_type_fqcn );
		$node_name = $node_ref->getShortName();

		$namespace             = self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Pagination';
		$node_type_class       = $node_name;
		$node_type_namespace   = self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Output';
		$node_type_alias       = $node_name . 'Type';
		$connection_class_name = $node_name . 'Connection';
		$edge_class_name       = $node_name . 'Edge';

		$connection_code = $this->generateConnectionCode( $namespace, $node_type_class, $node_type_namespace, $node_type_alias, $connection_class_name, $edge_class_name );
		$edge_code       = $this->generateEdgeCode( $namespace, $node_type_class, $node_type_namespace, $node_type_alias, $edge_class_name );

		file_put_contents(
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Pagination/' . $connection_class_name . '.php',
			$connection_code
		);
		file_put_contents(
			self::AUTOGENERATED_DIR . '/GraphQLTypes/Pagination/' . $edge_class_name . '.php',
			$edge_code
		);
	}

	private function generateConnectionCode( string $namespace, string $node_type_class, string $node_type_namespace, string $node_type_alias, string $connection_class_name, string $edge_class_name ): string {
		$code = "<?php\n\n";
		$code .= "declare(strict_types=1);\n\n";
		$code .= "// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.\n\n";
		$code .= "namespace {$namespace};\n\n";
		$code .= "use {$node_type_namespace}\\{$node_type_class} as {$node_type_alias};\n";
		$code .= "use GraphQL\\Type\\Definition\\ObjectType;\n";
		$code .= "use GraphQL\\Type\\Definition\\Type;\n\n";
		$code .= "class {$connection_class_name} {\n";
		$code .= "\tprivate static ?ObjectType \$instance = null;\n\n";
		$code .= "\tpublic static function get(): ObjectType {\n";
		$code .= "\t\tif (self::\$instance === null) {\n";
		$code .= "\t\t\tself::\$instance = new ObjectType([\n";
		$code .= "\t\t\t\t'name' => '{$connection_class_name}',\n";
		$code .= "\t\t\t\t'description' => 'A connection to a list of {$node_type_class} items.',\n";
		$code .= "\t\t\t\t'fields' => fn() => [\n";
		$code .= "\t\t\t\t\t'edges' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull(Type::listOf(Type::nonNull(\n";
		$code .= "\t\t\t\t\t\t\t{$edge_class_name}::get()\n";
		$code .= "\t\t\t\t\t\t))),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t\t'nodes' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull(Type::listOf(Type::nonNull(\n";
		$code .= "\t\t\t\t\t\t\t{$node_type_alias}::get()\n";
		$code .= "\t\t\t\t\t\t))),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t\t'page_info' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull(PageInfo::get()),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t\t'total_count' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull(Type::int()),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t],\n";
		$code .= "\t\t\t]);\n";
		$code .= "\t\t}\n";
		$code .= "\t\treturn self::\$instance;\n";
		$code .= "\t}\n";
		$code .= "}\n";

		return $code;
	}

	private function generateEdgeCode( string $namespace, string $node_type_class, string $node_type_namespace, string $node_type_alias, string $edge_class_name ): string {
		$code = "<?php\n\n";
		$code .= "declare(strict_types=1);\n\n";
		$code .= "// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.\n\n";
		$code .= "namespace {$namespace};\n\n";
		$code .= "use {$node_type_namespace}\\{$node_type_class} as {$node_type_alias};\n";
		$code .= "use GraphQL\\Type\\Definition\\ObjectType;\n";
		$code .= "use GraphQL\\Type\\Definition\\Type;\n\n";
		$code .= "class {$edge_class_name} {\n";
		$code .= "\tprivate static ?ObjectType \$instance = null;\n\n";
		$code .= "\tpublic static function get(): ObjectType {\n";
		$code .= "\t\tif (self::\$instance === null) {\n";
		$code .= "\t\t\tself::\$instance = new ObjectType([\n";
		$code .= "\t\t\t\t'name' => '{$edge_class_name}',\n";
		$code .= "\t\t\t\t'fields' => fn() => [\n";
		$code .= "\t\t\t\t\t'cursor' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull(Type::string()),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t\t'node' => [\n";
		$code .= "\t\t\t\t\t\t'type' => Type::nonNull({$node_type_alias}::get()),\n";
		$code .= "\t\t\t\t\t],\n";
		$code .= "\t\t\t\t],\n";
		$code .= "\t\t\t]);\n";
		$code .= "\t\t}\n";
		$code .= "\t\treturn self::\$instance;\n";
		$code .= "\t}\n";
		$code .= "}\n";

		return $code;
	}

	private function generatePageInfo(): void {
		$code = $this->renderTemplate( 'PageInfoTypeTemplate.php', [
			'namespace' => self::AUTOGENERATED_NAMESPACE . '\\GraphQLTypes\\Pagination',
		] );

		file_put_contents( self::AUTOGENERATED_DIR . '/GraphQLTypes/Pagination/PageInfo.php', $code );
	}

	// ------ FieldArgumentExtractor ------

	private function generateFieldArgumentExtractor(): void {
		$code = $this->renderTemplate( 'FieldArgumentExtractorTemplate.php', [
			'namespace' => self::AUTOGENERATED_NAMESPACE,
		] );

		file_put_contents( self::AUTOGENERATED_DIR . '/FieldArgumentExtractor.php', $code );
	}

	// ------ Root Types ------

	private function generateRootQueryType( array $queries ): void {
		$query_data = [];
		foreach ( $queries as $fqcn => $ref ) {
			$query_data[] = [
				'class_name'   => $ref->getShortName(),
				'fqcn'         => self::AUTOGENERATED_NAMESPACE . '\\GraphQLQueries\\' . $ref->getShortName(),
				'graphql_name' => $this->graphql_names[ $fqcn ],
			];
		}

		$code = $this->renderTemplate( 'RootQueryTypeTemplate.php', [
			'namespace' => self::AUTOGENERATED_NAMESPACE,
			'queries'   => $query_data,
		] );

		file_put_contents( self::AUTOGENERATED_DIR . '/RootQueryType.php', $code );
	}

	private function generateRootMutationType( array $mutations ): void {
		$mutation_data = [];
		foreach ( $mutations as $fqcn => $ref ) {
			$mutation_data[] = [
				'class_name'   => $ref->getShortName(),
				'fqcn'         => self::AUTOGENERATED_NAMESPACE . '\\GraphQLMutations\\' . $ref->getShortName(),
				'graphql_name' => $this->graphql_names[ $fqcn ],
			];
		}

		$code = $this->renderTemplate( 'RootMutationTypeTemplate.php', [
			'namespace' => self::AUTOGENERATED_NAMESPACE,
			'mutations' => $mutation_data,
		] );

		file_put_contents( self::AUTOGENERATED_DIR . '/RootMutationType.php', $code );
	}

	// ========================================================================
	// Helpers
	// ========================================================================

	private function writeTimestamp(): void {
		file_put_contents(
			self::AUTOGENERATED_DIR . '/api_generation_date.txt',
			(string) time()
		);
	}

	private function renderTemplate( string $template_name, array $vars ): string {
		extract( $vars );
		ob_start();
		require self::TEMPLATES_DIR . '/' . $template_name;
		return ob_get_clean();
	}

	private function getDescription( \ReflectionClass|\ReflectionEnum|\ReflectionEnumUnitCase $ref ): string {
		$attrs = $ref->getAttributes( Description::class );
		return ! empty( $attrs ) ? $attrs[0]->newInstance()->description : '';
	}

	private function getParamDescription( \ReflectionParameter $param ): string {
		$attrs = $param->getAttributes( Description::class );
		return ! empty( $attrs ) ? $attrs[0]->newInstance()->description : '';
	}

	private function getClassInfo( string $class_name ): ?array {
		return $this->classes[ $class_name ] ?? null;
	}

	private function buildFieldDefinition( \ReflectionProperty $prop, string $context, array &$use_stmts ): ?array {
		$type      = $prop->getType();
		$type_name = $type instanceof \ReflectionNamedType ? $type->getName() : 'mixed';
		$nullable  = $type?->allowsNull() ?? false;
		$has_default = $prop->hasDefaultValue();

		// For input types, nullable or has-default fields are optional (no nonNull wrapper).
		$is_optional = $context === 'input' && ( $nullable || $has_default );

		$type_expr = $this->phpTypeToGraphQLExpr( $type_name, $nullable || $is_optional, $prop, $use_stmts );

		$description = '';
		$desc_attrs  = $prop->getAttributes( Description::class );
		if ( ! empty( $desc_attrs ) ) {
			$description = $desc_attrs[0]->newInstance()->description;
		}

		$deprecation = $prop->getAttributes( Deprecated::class );

		// Field arguments (only for output types).
		$args = [];
		if ( $context === 'output' ) {
			$param_attrs = $prop->getAttributes( Parameter::class );
			foreach ( $param_attrs as $pa ) {
				$param_inst   = $pa->newInstance();
				$arg_type_expr = $this->paramTypeToGraphQLExpr( $param_inst, $use_stmts );
				$arg_entry = [
					'name'        => $param_inst->name,
					'type_expr'   => $arg_type_expr,
					'description' => $param_inst->description,
				];
				if ( $param_inst->has_default ) {
					$arg_entry['default'] = $param_inst->default;
				}
				$args[] = $arg_entry;
			}

			// Merge ParameterDescription.
			$pd_attrs = $prop->getAttributes( ParameterDescription::class );
			foreach ( $pd_attrs as $pda ) {
				$pd_inst = $pda->newInstance();
				foreach ( $args as &$arg ) {
					if ( $arg['name'] === $pd_inst->name && empty( $arg['description'] ) ) {
						$arg['description'] = $pd_inst->description;
					}
				}
			}
		}

		return [
			'name'               => $prop->getName(),
			'type_expr'          => $type_expr,
			'description'        => $description,
			'args'               => $args,
			'deprecation_reason' => ! empty( $deprecation ) ? $deprecation[0]->newInstance()->reason : null,
		];
	}

	private function phpTypeToGraphQLExpr( string $type_name, bool $nullable, \ReflectionProperty|\ReflectionParameter $context, array &$use_stmts ): string {
		// Check for ScalarType attribute.
		$scalar_attr = $context->getAttributes( ScalarType::class );
		if ( ! empty( $scalar_attr ) ) {
			$scalar_class = $scalar_attr[0]->newInstance()->type;
			$scalar_short = ( new \ReflectionClass( $scalar_class ) )->getShortName();
			$alias        = $scalar_short . 'Type';
			$use_stmts[]  = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Scalars\\{$scalar_short} as {$alias}";
			$expr         = "{$alias}::get()";
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Check for ArrayOf attribute.
		$array_of_attr = $context->getAttributes( ArrayOf::class );
		if ( ! empty( $array_of_attr ) && $type_name === 'array' ) {
			$item_type = $array_of_attr[0]->newInstance()->type;
			$item_expr = $this->typeStringToGraphQLExpr( $item_type, $use_stmts );
			$expr      = "Type::listOf(Type::nonNull({$item_expr}))";
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Check for ConnectionOf attribute.
		$conn_attr = $context->getAttributes( ConnectionOf::class );
		if ( ! empty( $conn_attr ) ) {
			$node_type = $conn_attr[0]->newInstance()->type;
			$node_short = ( new \ReflectionClass( $node_type ) )->getShortName();
			$conn_alias = $node_short . 'ConnectionType';
			$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Pagination\\{$node_short}Connection as {$conn_alias}";

			// Register the connection for generation.
			$this->connections[ $node_type ] = [
				'node_type' => $node_type,
				'source'    => $context instanceof \ReflectionProperty ? $context->getDeclaringClass()->getShortName() . '::$' . $context->getName() : 'return type',
			];

			$expr = "{$conn_alias}::get()";
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Primitive types.
		$primitive = match ( $type_name ) {
			'int'    => 'Type::int()',
			'float'  => 'Type::float()',
			'string' => 'Type::string()',
			'bool'   => 'Type::boolean()',
			default  => null,
		};

		if ( $primitive !== null ) {
			return $nullable ? $primitive : "Type::nonNull({$primitive})";
		}

		// Enum or type reference.
		$class_info = $this->getClassInfo( $type_name );
		if ( $class_info !== null ) {
			$short = ( new \ReflectionClass( $type_name ) )->getShortName();
			if ( $class_info['kind'] === 'enum' ) {
				$alias       = $short . 'Type';
				$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Enums\\{$short} as {$alias}";
				$expr        = "{$alias}::get()";
			} elseif ( $class_info['kind'] === 'type' ) {
				$expr = "{$short}::get()";
			} elseif ( $class_info['kind'] === 'input_type' ) {
				$gen_name = str_ends_with( $short, 'Input' ) ? substr( $short, 0, -5 ) : $short;
				$alias       = $gen_name . 'Input';
				$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Input\\{$gen_name} as {$alias}";
				$expr        = "{$alias}::get()";
			} else {
				$expr = "Type::string()"; // Fallback.
			}
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Unknown type — fallback to string.
		$this->warnings[] = "Unknown type '{$type_name}', falling back to String.";
		return $nullable ? 'Type::string()' : 'Type::nonNull(Type::string())';
	}

	private function typeStringToGraphQLExpr( string $type, array &$use_stmts ): string {
		// Primitive string references.
		return match ( $type ) {
			'int'    => 'Type::int()',
			'float'  => 'Type::float()',
			'string' => 'Type::string()',
			'bool'   => 'Type::boolean()',
			default  => $this->classTypeToGraphQLExpr( $type, $use_stmts ),
		};
	}

	private function classTypeToGraphQLExpr( string $fqcn, array &$use_stmts ): string {
		$class_info = $this->getClassInfo( $fqcn );
		if ( $class_info === null ) {
			$this->warnings[] = "Unknown class type '{$fqcn}' in ArrayOf.";
			return 'Type::string()';
		}

		$short = ( new \ReflectionClass( $fqcn ) )->getShortName();

		return match ( $class_info['kind'] ) {
			'enum' => ( function () use ( $short, &$use_stmts ) {
				$alias = $short . 'Type';
				$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Enums\\{$short} as {$alias}";
				return "{$alias}::get()";
			} )(),
			'type' => "{$short}::get()",
			default => 'Type::string()',
		};
	}

	private function paramTypeToGraphQLExpr( Parameter $param, array &$use_stmts ): string {
		$base = match ( $param->type ) {
			'int'    => 'Type::int()',
			'float'  => 'Type::float()',
			'string' => 'Type::string()',
			'bool'   => 'Type::boolean()',
			default  => $this->classTypeToGraphQLExpr( $param->type, $use_stmts ),
		};

		if ( $param->array ) {
			$base = "Type::listOf(Type::nonNull({$base}))";
		}

		if ( ! $param->nullable && ! $param->has_default ) {
			$base = "Type::nonNull({$base})";
		}

		return $base;
	}

	private function getReturnTypeExpr( \ReflectionMethod $method, array &$use_stmts ): string {
		$return_type = $method->getReturnType();
		if ( $return_type === null ) {
			return 'Type::string()';
		}

		$type_name = $return_type instanceof \ReflectionNamedType ? $return_type->getName() : 'mixed';
		$nullable  = $return_type->allowsNull();

		// Check for ConnectionOf on the method.
		$conn_attr = $method->getAttributes( ConnectionOf::class );
		if ( ! empty( $conn_attr ) ) {
			$node_type  = $conn_attr[0]->newInstance()->type;
			$node_short = ( new \ReflectionClass( $node_type ) )->getShortName();
			$conn_alias = $node_short . 'ConnectionType';
			$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Pagination\\{$node_short}Connection as {$conn_alias}";

			$this->connections[ $node_type ] = [
				'node_type' => $node_type,
				'source'    => $method->getDeclaringClass()->getShortName() . '::execute()',
			];

			$expr = "{$conn_alias}::get()";
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Output type reference.
		$class_info = $this->getClassInfo( $type_name );
		if ( $class_info !== null && $class_info['kind'] === 'type' ) {
			$short = ( new \ReflectionClass( $type_name ) )->getShortName();
			$alias = $short . 'Type';
			$use_stmts[] = self::AUTOGENERATED_NAMESPACE . "\\GraphQLTypes\\Output\\{$short} as {$alias}";
			$expr = "{$alias}::get()";
			return $nullable ? $expr : "Type::nonNull({$expr})";
		}

		// Primitive return.
		$primitive = match ( $type_name ) {
			'int'    => 'Type::int()',
			'float'  => 'Type::float()',
			'string' => 'Type::string()',
			'bool'   => 'Type::boolean()',
			default  => 'Type::string()',
		};

		return $nullable ? $primitive : "Type::nonNull({$primitive})";
	}

	private function toScreamingSnakeCase( string $pascalCase ): string {
		$result = preg_replace( '/([a-z])([A-Z])/', '$1_$2', $pascalCase );
		$result = preg_replace( '/([A-Z]+)([A-Z][a-z])/', '$1_$2', $result );
		return strtoupper( $result );
	}

	private function rmdirRecursive( string $dir ): void {
		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $dir, \FilesystemIterator::SKIP_DOTS ),
			\RecursiveIteratorIterator::CHILD_FIRST
		);

		foreach ( $iterator as $file ) {
			if ( $file->isDir() ) {
				rmdir( $file->getPathname() );
			} else {
				unlink( $file->getPathname() );
			}
		}

		rmdir( $dir );
	}
}
