<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api\Scripts;

class StalenessChecker {
	/**
	 * Returns true if the autogenerated code is stale (needs rebuilding).
	 */
	public static function isStale(): bool {
		$timestamp_file = __DIR__ . '/../Autogenerated/api_generation_date.txt';

		if ( ! file_exists( $timestamp_file ) ) {
			return true;
		}

		$generation_time = (int) file_get_contents( $timestamp_file );
		$api_dir         = __DIR__ . '/../../../Api';

		$iterator = new \RecursiveIteratorIterator(
			new \RecursiveDirectoryIterator( $api_dir, \FilesystemIterator::SKIP_DOTS )
		);

		foreach ( $iterator as $file ) {
			if ( $file->getExtension() === 'php' && $file->getMTime() > $generation_time ) {
				return true;
			}
		}

		return false;
	}
}
