<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums;

use Automattic\WooCommerce\Api\Enums\CouponStatus as CouponStatusEnum;
use GraphQL\Type\Definition\EnumType;

class CouponStatus {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if (self::$instance === null) {
			self::$instance = new EnumType([
				'name' => 'CouponStatus',
				'description' => 'The publication status of a coupon.',
				'values' => [
					'PUBLISHED' => [
						'value' => CouponStatusEnum::Published,
						'description' => 'The coupon is published and active.',
					],
					'DRAFT' => [
						'value' => CouponStatusEnum::Draft,
						'description' => 'The coupon is a draft.',
					],
					'PENDING' => [
						'value' => CouponStatusEnum::Pending,
						'description' => 'The coupon is pending review.',
					],
					'TRASH' => [
						'value' => CouponStatusEnum::Trash,
						'description' => 'The coupon is in the trash.',
					],
				],
			]);
		}
		return self::$instance;
	}
}
