<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums;

use Automattic\WooCommerce\Api\Enums\DiscountType as DiscountTypeEnum;
use GraphQL\Type\Definition\EnumType;

class DiscountType {
	private static ?EnumType $instance = null;

	public static function get(): EnumType {
		if (self::$instance === null) {
			self::$instance = new EnumType([
				'name' => 'DiscountType',
				'description' => 'The type of discount for a coupon.',
				'values' => [
					'PERCENT' => [
						'value' => DiscountTypeEnum::Percent,
						'description' => 'A percentage discount.',
					],
					'FIXED_CART' => [
						'value' => DiscountTypeEnum::FixedCart,
						'description' => 'A fixed amount discount applied to the cart.',
					],
					'FIXED_PRODUCT' => [
						'value' => DiscountTypeEnum::FixedProduct,
						'description' => 'A fixed amount discount applied to each eligible product.',
					],
				],
			]);
		}
		return self::$instance;
	}
}
