<?php

declare(strict_types=1);

namespace Automattic\WooCommerce\Internal\Api;

use Automattic\WooCommerce\Api\ApiException;
use Automattic\WooCommerce\Internal\Api\Autogenerated\RootQueryType;
use Automattic\WooCommerce\Internal\Api\Autogenerated\RootMutationType;
use GraphQL\GraphQL;
use GraphQL\Type\Schema;
use GraphQL\Error\DebugFlag;

class GraphQLController {
	private ?Schema $schema = null;

	/**
	 * Register the GraphQL REST route.
	 */
	public function register(): void {
		register_rest_route( 'wc/v4', '/graphql', array(
			'methods'             => array( 'GET', 'POST' ),
			'callback'            => array( $this, 'handle_request' ),
			'permission_callback' => '__return_true', // Auth is handled per-query/mutation.
		) );
	}

	/**
	 * Handle an incoming GraphQL request.
	 */
	public function handle_request( \WP_REST_Request $request ): \WP_REST_Response {
		// 1. PHP version check.
		if ( PHP_VERSION_ID < 80100 ) {
			return $this->php_version_error_response( $request );
		}

		// 2. Parse request.
		$query          = $request->get_param( 'query' );
		$variables      = $request->get_param( 'variables' ) ?? array();
		$operation_name = $request->get_param( 'operationName' );

		// GET requests send variables as a JSON-encoded string.
		if ( is_string( $variables ) ) {
			$variables = json_decode( $variables, true ) ?? array();
		}

		if ( empty( $query ) ) {
			return new \WP_REST_Response(
				array(
					'errors' => array(
						array(
							'message'    => 'No query provided.',
							'extensions' => array( 'code' => 'BAD_REQUEST' ),
						),
					),
				),
				400
			);
		}

		// 3. Load schema.
		$schema = $this->get_schema();

		// 4. Execute.
		try {
			$result = GraphQL::executeQuery(
				schema: $schema,
				source: $query,
				variableValues: $variables,
				operationName: $operation_name,
			);

			$debug_flags = $this->get_debug_flags( $request );
			$output      = $result->toArray( $debug_flags );
		} catch ( \Throwable $e ) {
			$output = array(
				'errors' => array(
					$this->format_exception( $e, $request ),
				),
			);
		}

		// 5. Determine HTTP status code.
		$status = 200;
		if ( isset( $output['errors'] ) && ! isset( $output['data'] ) ) {
			$status = $this->get_error_status( $output['errors'] );
		}

		return new \WP_REST_Response( $output, $status );
	}

	/**
	 * Build and cache the GraphQL schema.
	 */
	private function get_schema(): Schema {
		if ( $this->schema === null ) {
			$this->schema = new Schema( array(
				'query'    => RootQueryType::get(),
				'mutation' => RootMutationType::get(),
			) );
		}
		return $this->schema;
	}

	/**
	 * Determine debug flags based on WP_DEBUG, user role, and query string.
	 */
	private function get_debug_flags( \WP_REST_Request $request ): int {
		if ( ! $this->is_debug_mode( $request ) ) {
			return DebugFlag::NONE;
		}
		return DebugFlag::INCLUDE_DEBUG_MESSAGE | DebugFlag::INCLUDE_TRACE;
	}

	/**
	 * Check if debug mode is active.
	 *
	 * Debug mode is active when either:
	 * - WP_DEBUG is enabled AND the current user is an administrator (or in a local environment).
	 * - The current user is an administrator (or in a local environment) AND `_debug=1` is in the query string.
	 */
	private function is_debug_mode( \WP_REST_Request $request ): bool {
		if ( ! $this->is_local_environment() && ! current_user_can( 'manage_options' ) ) {
			return false;
		}

		if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
			return true;
		}

		// phpcs:ignore WordPress.Security.NonceVerification
		return isset( $_GET['_debug'] ) && $_GET['_debug'] === '1';
	}

	/**
	 * Return a fixed error for PHP < 8.1.
	 */
	private function php_version_error_response( \WP_REST_Request $request ): \WP_REST_Response {
		$message = 'The GraphQL API is not available on this server.';

		if ( $this->is_debug_mode( $request ) ) {
			$message .= sprintf(
				' Reason: PHP 8.1 or later is required. Current version: %s.',
				PHP_VERSION
			);
		}

		return new \WP_REST_Response(
			array(
				'errors' => array(
					array( 'message' => $message ),
				),
			),
			500
		);
	}

	/**
	 * Format a caught exception into a GraphQL error array.
	 */
	private function format_exception( \Throwable $e, \WP_REST_Request $request ): array {
		if ( $e instanceof ApiException ) {
			$error = array(
				'message'    => $e->getMessage(),
				'extensions' => array_merge(
					array( 'code' => $e->getErrorCode() ),
					$e->getExtensions()
				),
			);
		} elseif ( $e instanceof \InvalidArgumentException ) {
			$error = array(
				'message'    => $e->getMessage(),
				'extensions' => array( 'code' => 'INVALID_ARGUMENT' ),
			);
		} else {
			$error = array(
				'message'    => 'An unexpected error occurred.',
				'extensions' => array( 'code' => 'INTERNAL_ERROR' ),
			);
		}

		if ( $this->is_debug_mode( $request ) ) {
			$error['extensions']['debug'] = array(
				'message' => $e->getMessage(),
				'file'    => $e->getFile(),
				'line'    => $e->getLine(),
				'trace'   => $e->getTraceAsString(),
			);
		}

		return $error;
	}

	/**
	 * Determine the HTTP status code from an array of GraphQL errors.
	 */
	private function get_error_status( array $errors ): int {
		foreach ( $errors as $error ) {
			$code = $error['extensions']['code'] ?? null;
			if ( $code === 'UNAUTHORIZED' ) {
				return 401;
			}
		}
		return 500;
	}

	/**
	 * Check if running in a local/development environment.
	 */
	private function is_local_environment(): bool {
		if ( function_exists( 'wp_get_environment_type' ) && wp_get_environment_type() === 'local' ) {
			return true;
		}

		$site_url = get_site_url();
		return str_contains( $site_url, 'localhost' ) || str_contains( $site_url, '127.0.0.1' );
	}
}
