<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\DiscountType as DiscountTypeType;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\CouponStatus as CouponStatusType;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Scalars\DateTime as DateTimeType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

class Coupon {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if (self::$instance === null) {
			self::$instance = new ObjectType([
				'name' => 'Coupon',
				'description' => 'Represents a WooCommerce discount coupon.',
				'fields' => fn() => [
					'id' => [
						'type' => Type::nonNull(Type::int()),
						'description' => 'The coupon ID.',
					],
					'code' => [
						'type' => Type::nonNull(Type::string()),
						'description' => 'The coupon code.',
					],
					'description' => [
						'type' => Type::nonNull(Type::string()),
						'description' => 'The coupon description.',
					],
					'discount_type' => [
						'type' => Type::nonNull(DiscountTypeType::get()),
						'description' => 'The type of discount.',
					],
					'amount' => [
						'type' => Type::nonNull(Type::float()),
						'description' => 'The discount amount.',
					],
					'status' => [
						'type' => Type::nonNull(CouponStatusType::get()),
						'description' => 'The coupon status.',
					],
					'date_created' => [
						'type' => DateTimeType::get(),
						'description' => 'The date the coupon was created.',
					],
					'date_modified' => [
						'type' => DateTimeType::get(),
						'description' => 'The date the coupon was last modified.',
					],
					'date_expires' => [
						'type' => DateTimeType::get(),
						'description' => 'The date the coupon expires.',
					],
					'usage_count' => [
						'type' => Type::nonNull(Type::int()),
						'description' => 'The number of times the coupon has been used.',
					],
					'individual_use' => [
						'type' => Type::nonNull(Type::boolean()),
						'description' => 'Whether the coupon can only be used alone.',
					],
					'product_ids' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::int()))),
						'description' => 'Product IDs the coupon can be applied to.',
					],
					'excluded_product_ids' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::int()))),
						'description' => 'Product IDs excluded from the coupon.',
					],
					'usage_limit' => [
						'type' => Type::nonNull(Type::int()),
						'description' => 'Maximum number of times the coupon can be used in total.',
					],
					'usage_limit_per_user' => [
						'type' => Type::nonNull(Type::int()),
						'description' => 'Maximum number of times the coupon can be used per customer.',
					],
					'limit_usage_to_x_items' => [
						'type' => Type::int(),
						'description' => 'Maximum number of items the coupon can be applied to.',
					],
					'free_shipping' => [
						'type' => Type::nonNull(Type::boolean()),
						'description' => 'Whether the coupon grants free shipping.',
					],
					'product_categories' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::int()))),
						'description' => 'Product category IDs the coupon applies to.',
					],
					'excluded_product_categories' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::int()))),
						'description' => 'Product category IDs excluded from the coupon.',
					],
					'exclude_sale_items' => [
						'type' => Type::nonNull(Type::boolean()),
						'description' => 'Whether the coupon excludes items on sale.',
					],
					'minimum_amount' => [
						'type' => Type::nonNull(Type::float()),
						'description' => 'Minimum order amount required to use the coupon.',
					],
					'maximum_amount' => [
						'type' => Type::nonNull(Type::float()),
						'description' => 'Maximum order amount allowed to use the coupon.',
					],
					'email_restrictions' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::string()))),
						'description' => 'Email addresses that can use this coupon.',
					],
					'used_by' => [
						'type' => Type::nonNull(Type::listOf(Type::nonNull(Type::string()))),
						'description' => 'Email addresses of customers who have used this coupon.',
					],
				],
			]);
		}
		return self::$instance;
	}
}
