<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output;

use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

class DeleteCouponResult {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if (self::$instance === null) {
			self::$instance = new ObjectType([
				'name' => 'DeleteCouponResult',
				'description' => 'The result of deleting a coupon.',
				'fields' => fn() => [
					'id' => [
						'type' => Type::nonNull(Type::int()),
						'description' => 'The ID of the deleted coupon.',
					],
					'deleted' => [
						'type' => Type::nonNull(Type::boolean()),
						'description' => 'Whether the coupon was permanently deleted.',
					],
				],
			]);
		}
		return self::$instance;
	}
}
