<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Scalars;

use Automattic\WooCommerce\Api\Scalars\DateTime as DateTimeScalar;
use GraphQL\Type\Definition\CustomScalarType;

class DateTime {
	private static ?CustomScalarType $instance = null;

	public static function get(): CustomScalarType {
		if (self::$instance === null) {
			self::$instance = new CustomScalarType([
				'name' => 'DateTime',
				'description' => 'An ISO 8601 encoded date and time string.',
				'serialize' => fn($value) => DateTimeScalar::serialize($value),
				'parseValue' => fn($value) => DateTimeScalar::parse($value),
				'parseLiteral' => function ($valueNode, ?array $variables = null) {
					if ($valueNode instanceof \GraphQL\Language\AST\StringValueNode) {
						return DateTimeScalar::parse($valueNode->value);
					}
					throw new \GraphQL\Error\Error(
						'DateTime must be a string, got: ' . $valueNode->kind
					);
				},
			]);
		}
		return self::$instance;
	}
}
