<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Input;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\DiscountType as DiscountTypeType;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\CouponStatus as CouponStatusType;
use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;

class UpdateCoupon {
	private static ?InputObjectType $instance = null;

	public static function get(): InputObjectType {
		if (self::$instance === null) {
			self::$instance = new InputObjectType([
				'name' => 'UpdateCouponInput',
				'description' => 'Data for updating an existing coupon. All fields are optional.',
				'fields' => fn() => [
					'code' => [
						'type' => Type::string(),
						'description' => 'The coupon code.',
					],
					'description' => [
						'type' => Type::string(),
						'description' => 'The coupon description.',
					],
					'discount_type' => [
						'type' => DiscountTypeType::get(),
						'description' => 'The type of discount.',
					],
					'amount' => [
						'type' => Type::float(),
						'description' => 'The discount amount.',
					],
					'status' => [
						'type' => CouponStatusType::get(),
						'description' => 'The coupon status.',
					],
					'date_expires' => [
						'type' => Type::string(),
						'description' => 'The date the coupon expires (ISO 8601).',
					],
					'individual_use' => [
						'type' => Type::boolean(),
						'description' => 'Whether the coupon can only be used alone.',
					],
					'product_ids' => [
						'type' => Type::listOf(Type::nonNull(Type::int())),
						'description' => 'Product IDs the coupon can be applied to.',
					],
					'excluded_product_ids' => [
						'type' => Type::listOf(Type::nonNull(Type::int())),
						'description' => 'Product IDs excluded from the coupon.',
					],
					'usage_limit' => [
						'type' => Type::int(),
						'description' => 'Maximum number of times the coupon can be used in total.',
					],
					'usage_limit_per_user' => [
						'type' => Type::int(),
						'description' => 'Maximum number of times the coupon can be used per customer.',
					],
					'limit_usage_to_x_items' => [
						'type' => Type::int(),
						'description' => 'Maximum number of items the coupon can be applied to.',
					],
					'free_shipping' => [
						'type' => Type::boolean(),
						'description' => 'Whether the coupon grants free shipping.',
					],
					'product_categories' => [
						'type' => Type::listOf(Type::nonNull(Type::int())),
						'description' => 'Product category IDs the coupon applies to.',
					],
					'excluded_product_categories' => [
						'type' => Type::listOf(Type::nonNull(Type::int())),
						'description' => 'Product category IDs excluded from the coupon.',
					],
					'exclude_sale_items' => [
						'type' => Type::boolean(),
						'description' => 'Whether the coupon excludes items on sale.',
					],
					'minimum_amount' => [
						'type' => Type::float(),
						'description' => 'Minimum order amount required to use the coupon.',
					],
					'maximum_amount' => [
						'type' => Type::float(),
						'description' => 'Maximum order amount allowed to use the coupon.',
					],
					'email_restrictions' => [
						'type' => Type::listOf(Type::nonNull(Type::string())),
						'description' => 'Email addresses that can use this coupon.',
					],
				],
			]);
		}
		return self::$instance;
	}
}
