<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use Automattic\WooCommerce\Api\Queries\GetCoupon as GetCouponCommand;
use Automattic\WooCommerce\Api\ApiException;
use Automattic\WooCommerce\Internal\Api\Autogenerated\FieldArgumentExtractor;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\Coupon as CouponType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class GetCoupon {
	public static function getFieldDefinition(): array {
		return [
			'type' => CouponType::get(),
			'description' => 'Retrieve a single coupon by ID or code. Exactly one of the two arguments must be provided.',
			'args' => [
				'id' => [
					'type' => Type::int(),
					'description' => 'The ID of the coupon to retrieve.',
					'defaultValue' => NULL,
				],
				'code' => [
					'type' => Type::string(),
					'description' => 'The coupon code to look up.',
					'defaultValue' => NULL,
				],
			],
			'resolve' => [self::class, 'resolve'],
		];
	}

	public static function resolve(mixed $root, array $args, mixed $context, ResolveInfo $info): mixed {
		$command = wc_get_container()->get(GetCouponCommand::class);

		$execute_args = [];
		if (array_key_exists('id', $args)) {
			$execute_args['id'] = $args['id'];
		}
		if (array_key_exists('code', $args)) {
			$execute_args['code'] = $args['code'];
		}

		try {
			$result = $command->execute(...$execute_args);
		} catch (ApiException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: array_merge(
					['code' => $e->getErrorCode()],
					$e->getExtensions()
				)
			);
		} catch (\InvalidArgumentException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: ['code' => 'INVALID_ARGUMENT']
			);
		} catch (\Throwable $e) {
			throw new \GraphQL\Error\Error(
				'An unexpected error occurred.',
				previous: $e
			);
		}

		return $result;
	}
}
