<?php
declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLQueries;

use Automattic\WooCommerce\Api\Queries\ListCoupons as ListCouponsCommand;
use Automattic\WooCommerce\Api\ApiException;
use Automattic\WooCommerce\Internal\Api\Autogenerated\FieldArgumentExtractor;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Pagination\CouponConnection as CouponConnectionType;
use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Enums\CouponStatus as CouponStatusType;
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class ListCoupons {
	public static function getFieldDefinition(): array {
		return [
			'type' => Type::nonNull(CouponConnectionType::get()),
			'description' => 'List coupons with cursor-based pagination.',
			'args' => [
				'first' => [
					'type' => Type::int(),
					'description' => 'Return the first N results.',
					'defaultValue' => NULL,
				],
				'last' => [
					'type' => Type::int(),
					'description' => 'Return the last N results.',
					'defaultValue' => NULL,
				],
				'after' => [
					'type' => Type::string(),
					'description' => 'Return results after this cursor.',
					'defaultValue' => NULL,
				],
				'before' => [
					'type' => Type::string(),
					'description' => 'Return results before this cursor.',
					'defaultValue' => NULL,
				],
				'status' => [
					'type' => CouponStatusType::get(),
					'description' => 'Filter by coupon status.',
					'defaultValue' => NULL,
				],
			],
			'resolve' => [self::class, 'resolve'],
		];
	}

	public static function resolve(mixed $root, array $args, mixed $context, ResolveInfo $info): mixed {
		$command = wc_get_container()->get(ListCouponsCommand::class);

		$execute_args = [];
		$execute_args['pagination'] = new \Automattic\WooCommerce\Api\Pagination\PaginationParams(
			first: $args['first'] ?? NULL,
			last: $args['last'] ?? NULL,
			after: $args['after'] ?? NULL,
			before: $args['before'] ?? NULL,
		);
		if (array_key_exists('status', $args)) {
			$execute_args['status'] = $args['status'] !== null ? \Automattic\WooCommerce\Api\Enums\CouponStatus::from($args['status']) : null;
		}

		try {
			$result = $command->execute(...$execute_args);
		} catch (ApiException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: array_merge(
					['code' => $e->getErrorCode()],
					$e->getExtensions()
				)
			);
		} catch (\InvalidArgumentException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: ['code' => 'INVALID_ARGUMENT']
			);
		} catch (\Throwable $e) {
			throw new \GraphQL\Error\Error(
				'An unexpected error occurred.',
				previous: $e
			);
		}

		return $result;
	}
}
