<?php
/**
 * Template for generating a query/mutation resolver class.
 *
 * @var string $namespace
 * @var string $class_name
 * @var string $graphql_name
 * @var string $description
 * @var string $command_fqcn
 * @var string $command_alias
 * @var string $return_type_expr
 * @var array  $use_statements
 * @var array  $args - each: ['name', 'type_expr', 'description', 'has_default', 'default']
 * @var array  $capabilities
 * @var bool   $public_access
 * @var bool   $has_connection_of
 * @var string $connection_type_alias
 * @var array  $execute_params - each: ['name', 'conversion' => ?string, 'is_infrastructure' => bool, 'unroll' => ?array]
 * @var array  $input_converters - each: ['method_name', 'input_fqcn', 'input_class', 'properties' => [['name', 'conversion']]]
 */

$escaped_description = addslashes( $description );
$has_cap_check       = ! $public_access && ! empty( $capabilities );
?>
<?= '<?php' ?>

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace <?= $namespace ?>;

use <?= $command_fqcn ?> as <?= $command_alias ?>;
use Automattic\WooCommerce\Api\ApiException;
use Automattic\WooCommerce\Internal\Api\Autogenerated\FieldArgumentExtractor;
<?php foreach ( $use_statements as $use ) : ?>
use <?= $use ?>;
<?php endforeach; ?>
use GraphQL\Type\Definition\ResolveInfo;
use GraphQL\Type\Definition\Type;

class <?= $class_name ?> {
	public static function getFieldDefinition(): array {
		return [
			'type' => <?= $return_type_expr ?>,
<?php if ( $description !== '' ) : ?>
			'description' => '<?= $escaped_description ?>',
<?php endif; ?>
			'args' => [
<?php foreach ( $args as $arg ) : ?>
				'<?= $arg['name'] ?>' => [
					'type' => <?= $arg['type_expr'] ?>,
<?php if ( ! empty( $arg['description'] ) ) : ?>
					'description' => '<?= addslashes( $arg['description'] ) ?>',
<?php endif; ?>
<?php if ( $arg['has_default'] ) : ?>
					'defaultValue' => <?= var_export( $arg['default'], true ) ?>,
<?php endif; ?>
				],
<?php endforeach; ?>
			],
			'resolve' => [self::class, 'resolve'],
		];
	}

	public static function resolve(mixed $root, array $args, mixed $context, ResolveInfo $info): mixed {
<?php if ( $has_cap_check ) : ?>
		self::checkCapabilities();

<?php endif; ?>
		$command = wc_get_container()->get(<?= $command_alias ?>::class);

		$execute_args = [];
<?php foreach ( $execute_params as $param ) : ?>
<?php if ( ! empty( $param['unroll'] ) ) : ?>
		$execute_args['<?= $param['name'] ?>'] = new \<?= $param['unroll']['fqcn'] ?>(
<?php foreach ( $param['unroll']['properties'] as $uprop ) : ?>
			<?= $uprop['name'] ?>: <?= $uprop['value_expr'] ?>,
<?php endforeach; ?>
		);
<?php elseif ( $param['is_infrastructure'] && $param['name'] === '_requested_fields' ) : ?>
		$execute_args['_requested_fields'] = self::extractRequestedFields($info);
<?php elseif ( $param['is_infrastructure'] && $param['name'] === '_field_arguments' ) : ?>
		$execute_args['_field_arguments'] = FieldArgumentExtractor::extract($info->fieldNodes[0]->selectionSet ?? null, $info->variableValues);
<?php elseif ( ! empty( $param['conversion'] ) ) : ?>
		if (array_key_exists('<?= $param['name'] ?>', $args)) {
			$execute_args['<?= $param['name'] ?>'] = <?= $param['conversion'] ?>;
		}
<?php else : ?>
		if (array_key_exists('<?= $param['name'] ?>', $args)) {
			$execute_args['<?= $param['name'] ?>'] = $args['<?= $param['name'] ?>'];
		}
<?php endif; ?>
<?php endforeach; ?>

		try {
			$result = $command->execute(...$execute_args);
		} catch (ApiException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: array_merge(
					['code' => $e->getErrorCode()],
					$e->getExtensions()
				)
			);
		} catch (\InvalidArgumentException $e) {
			throw new \GraphQL\Error\Error(
				$e->getMessage(),
				extensions: ['code' => 'INVALID_ARGUMENT']
			);
		} catch (\Throwable $e) {
			throw new \GraphQL\Error\Error(
				'An unexpected error occurred.',
				previous: $e
			);
		}

		return $result;
	}
<?php if ( $has_cap_check ) : ?>

	private static function checkCapabilities(): void {
		$required = <?= var_export( $capabilities, true ) ?>;
		foreach ($required as $cap) {
			if (!current_user_can($cap)) {
				throw new \GraphQL\Error\Error(
					'You do not have permission to perform this action.',
					extensions: ['code' => 'UNAUTHORIZED']
				);
			}
		}
	}
<?php endif; ?>
<?php foreach ( $input_converters as $converter ) : ?>

	private static function <?= $converter['method_name'] ?>(array $data): \<?= $converter['input_fqcn'] ?> {
		$input = new \<?= $converter['input_fqcn'] ?>();

<?php foreach ( $converter['properties'] as $prop ) : ?>
		if (array_key_exists('<?= $prop['name'] ?>', $data)) {
<?php if ( ! empty( $prop['conversion'] ) ) : ?>
			$input-><?= $prop['name'] ?> = <?= $prop['conversion'] ?>;
<?php else : ?>
			$input-><?= $prop['name'] ?> = $data['<?= $prop['name'] ?>'];
<?php endif; ?>
		}
<?php endforeach; ?>

		return $input;
	}
<?php endforeach; ?>
}
