<?php

declare(strict_types=1);

// THIS FILE IS AUTO-GENERATED. DO NOT EDIT MANUALLY.

namespace Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Pagination;

use Automattic\WooCommerce\Internal\Api\Autogenerated\GraphQLTypes\Output\Coupon as CouponType;
use GraphQL\Type\Definition\ObjectType;
use GraphQL\Type\Definition\Type;

class CouponEdge {
	private static ?ObjectType $instance = null;

	public static function get(): ObjectType {
		if (self::$instance === null) {
			self::$instance = new ObjectType([
				'name' => 'CouponEdge',
				'fields' => fn() => [
					'cursor' => [
						'type' => Type::nonNull(Type::string()),
					],
					'node' => [
						'type' => Type::nonNull(CouponType::get()),
					],
				],
			]);
		}
		return self::$instance;
	}
}
